[package]
name = "parachain-template-node"
version = "0.1.0"
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a parachain."
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/cumulus/"
edition = "2021"
build = "build.rs"

[[bin]]
name = "parachain-collator"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
derive_more = "0.99.2"
log = "0.4.17"
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.137", features = ["derive"] }
hex-literal = "0.3.4"
jsonrpsee = { version = "0.14.0", features = ["server"] }

# Local
parachain-template-runtime = { path = "../runtime" }

# Substrate
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-cli = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"] , branch = "bkchr-state-access-benchmark" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-executor = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"] , branch = "bkchr-state-access-benchmark" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-service = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"] , branch = "bkchr-state-access-benchmark" }
sc-sysinfo = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }

# Polkadot
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "bkchr-new-trie-cache" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "bkchr-new-trie-cache" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "bkchr-new-trie-cache" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "bkchr-new-trie-cache" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "bkchr-new-trie-cache" }

# Cumulus
cumulus-client-cli = { path = "../../client/cli" }
cumulus-client-collator = { path = "../../client/collator" }
cumulus-client-consensus-aura = { path = "../../client/consensus/aura" }
cumulus-client-consensus-common = { path = "../../client/consensus/common" }
cumulus-client-network = { path = "../../client/network" }
cumulus-client-service = { path = "../../client/service" }
cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-primitives-parachain-inherent = { path = "../../primitives/parachain-inherent" }
cumulus-relay-chain-inprocess-interface = { path = "../../client/relay-chain-inprocess-interface" }
cumulus-relay-chain-interface = { path = "../../client/relay-chain-interface" }
cumulus-relay-chain-rpc-interface = { path = "../../client/relay-chain-rpc-interface" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }

[features]
default = []
runtime-benchmarks = [
	"parachain-template-runtime/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
]
try-runtime = ["parachain-template-runtime/try-runtime"]
