[package]
name = "cumulus-primitives-utility"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive" ] }

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "bkchr-state-access-benchmark" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "bkchr-state-access-benchmark" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "bkchr-state-access-benchmark" }
sp-trie = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "bkchr-state-access-benchmark" }

# Polkadot
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "bkchr-new-trie-cache" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "bkchr-new-trie-cache" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "bkchr-new-trie-cache" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "bkchr-new-trie-cache" }

# Cumulus
cumulus-primitives-core = { path = "../core", default-features = false }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain/std",
	"polkadot-primitives/std",
	"cumulus-primitives-core/std",
]
