[package]
name = "cumulus-client-consensus-aura"
description = "AURA consensus algorithm for parachains"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.56"
codec = { package = "parity-scale-codec", version = "3.0.0", features = [ "derive" ] }
futures = { version = "0.3.8", features = ["compat"] }
tracing = "0.1.34"

# Substrate
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "bkchr-state-access-benchmark" }

# Cumulus
cumulus-client-consensus-common = { path = "../common" }
cumulus-primitives-core = { path = "../../../primitives/core" }
